<?php

/**
 * Administrasi_Model_Base_DaftarObat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nama
 * @property string $code
 * @property string $type_obat
 * @property string $produsen
 * @property boolean $isgeneric
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_DaftarObat extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('daftar_obat');
        $this->hasColumn('nama', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('code', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('type_obat', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('produsen', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('isgeneric', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}