<?php

/**
 * Administrasi_Model_Base_Pasien
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nama
 * @property date $tgllahir
 * @property enum $jnskelamin
 * @property enum $goldarah
 * @property string $alamat
 * @property string $telepon
 * @property string $email
 * @property string $catatan
 * @property Doctrine_Collection $Administrasi_Model_Periksa
 * @property Doctrine_Collection $Administrasi_Model_PasienAlergi
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_Pasien extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('pasien');
        $this->hasColumn('nama', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('tgllahir', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('jnskelamin', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'L',
              1 => 'P',
             ),
             ));
        $this->hasColumn('goldarah', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'A',
              1 => 'B',
              2 => 'AB',
              3 => 0,
             ),
             ));
        $this->hasColumn('alamat', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('telepon', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('catatan', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Administrasi_Model_Periksa', array(
             'local' => 'id',
             'foreign' => 'pasien_id'));

        $this->hasMany('Administrasi_Model_PasienAlergi', array(
             'local' => 'id',
             'foreign' => 'pasien_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}