<?php

/**
 * Administrasi_Model_Base_PasienAlergi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pasien_id
 * @property string $alergi
 * @property string $catatan
 * @property Administrasi_Model_Pasien $Pasien
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_PasienAlergi extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('pasien_alergi');
        $this->hasColumn('pasien_id', 'integer', 6, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '6',
             ));
        $this->hasColumn('alergi', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('catatan', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Administrasi_Model_Pasien as Pasien', array(
             'local' => 'pasien_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}