<?php

/**
 * Administrasi_Model_Base_Periksa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pasien_id
 * @property string $type_pemeriksaan
 * @property integer $no_urut
 * @property string $penyakit
 * @property integer $referensi_riwayat
 * @property string $diagnosa
 * @property string $pengobatan
 * @property string $catatan
 * @property boolean $status
 * @property Administrasi_Model_Pasien $Pasien
 * @property Doctrine_Collection $Administrasi_Model_PeriksaObat
 * @property Doctrine_Collection $Administrasi_Model_PeriksaKeluhan
 * @property Doctrine_Collection $Administrasi_Model_PeriksaDiagnosa
 * @property Doctrine_Collection $Administrasi_Model_PeriksaResep
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_Periksa extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('periksa');
        $this->hasColumn('pasien_id', 'integer', 6, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '6',
             ));
        $this->hasColumn('type_pemeriksaan', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('no_urut', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('penyakit', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('referensi_riwayat', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('diagnosa', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('pengobatan', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('catatan', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Administrasi_Model_Pasien as Pasien', array(
             'local' => 'pasien_id',
             'foreign' => 'id'));

        $this->hasMany('Administrasi_Model_PeriksaObat', array(
             'local' => 'id',
             'foreign' => 'periksa_id'));

        $this->hasMany('Administrasi_Model_PeriksaKeluhan', array(
             'local' => 'id',
             'foreign' => 'periksa_id'));

        $this->hasMany('Administrasi_Model_PeriksaDiagnosa', array(
             'local' => 'id',
             'foreign' => 'periksa_id'));

        $this->hasMany('Administrasi_Model_PeriksaResep', array(
             'local' => 'id',
             'foreign' => 'periksa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}