<?php

/**
 * Administrasi_Model_Base_PeriksaObat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periksa_id
 * @property string $obat
 * @property string $dosis
 * @property Administrasi_Model_Periksa $Periksa:
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Administrasi_Model_Base_PeriksaObat extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('periksa_obat');
        $this->hasColumn('periksa_id', 'integer', 6, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '6',
             ));
        $this->hasColumn('obat', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('dosis', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Administrasi_Model_Periksa as Periksa:', array(
             'local' => 'periksa_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}