<?= $this->doctype() ?>
<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
    </head>
    <body>
        <div class="container-fluid">
            <?= $this->layout()->content; ?>
        </div>
    </body>

        <?= $this->JQuery() ?>
        <?= $this->headScript() ?>
</html>