<?php

/**
 * Administrasi_Model_PeriksaObat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Administrasi_Model_PeriksaObat extends Administrasi_Model_Base_PeriksaObat
{

}